#!/bin/bash
if test $1
then
        VERSION=$1-
else
        VERSION=""
fi
TGZNAME=keller/nmring-$VERSION$(date +%Y%m%d_%H_%M).tgz
mkdir -p keller
tar cvzf $TGZNAME *.h *.cpp Makefile README autotar
echo \=\>$TGZNAME
